"""
Tests for HawkesMLE calibration, GoF diagnostics, and CalibrationResult I/O.

All tests use synthetic Hawkes data generated by thinning (Ogata, 1981).
"""
from __future__ import annotations

import json
import tempfile
from pathlib import Path

import numpy as np
import pytest

from quantflow.calibration.hawkes_mle import (
    HawkesMLE,
    HawkesParams,
    CalibrationResult,
    _merge_events,
)
from quantflow.calibration.goodness_of_fit import HawkesGoodnessOfFit


# ── synthetic Hawkes simulation ───────────────────────────────────────────────


def simulate_hawkes_1d(
    mu:    float,
    alpha: float,
    beta:  float,
    T:     float,
    seed:  int = 0,
) -> np.ndarray:
    """
    Simulate a 1-D Hawkes process via Ogata's thinning algorithm.
    Returns sorted event times in [0, T).
    """
    rng    = np.random.default_rng(seed)
    events = []
    t      = 0.0

    # λ*(t) = mu + alpha * Σ_{s<t} exp(-beta*(t-s))
    running_sum = 0.0   # Σ exp(-beta*(t-s)) at current t

    while t < T:
        # Upper bound on intensity at current t
        lam_bar = mu + alpha * running_sum + alpha   # +alpha for potential new event

        # Draw next candidate time
        dt = rng.exponential(1.0 / lam_bar)
        t += dt
        if t >= T:
            break

        # Update running sum for new t
        running_sum *= np.exp(-beta * dt)

        # Actual intensity at t
        lam_t = mu + alpha * running_sum

        # Accept / reject
        if rng.uniform() <= lam_t / lam_bar:
            events.append(t)
            running_sum += 1.0  # include this event in future sums

    return np.array(events, dtype=np.float64)


def simulate_hawkes_2d(
    mu:    np.ndarray,      # (2,)
    alpha: np.ndarray,      # (2, 2)
    beta:  np.ndarray,      # (2, 2)
    T:     float,
    seed:  int = 0,
) -> list[np.ndarray]:
    """
    Simulate a 2-D Hawkes process via Ogata's thinning.
    Returns [times_dim0, times_dim1].
    """
    rng    = np.random.default_rng(seed)
    events: list[list[float]] = [[], []]
    t      = 0.0
    R      = np.zeros((2, 2))   # R[i, j] = Σ_{s<t, dim=j} exp(-beta[i,j]*(t-s))

    while t < T:
        # Upper bound: evaluate each dim's max intensity
        lam_upper = np.zeros(2)
        for i in range(2):
            lam_upper[i] = mu[i] + np.sum(alpha[i] * R[i]) + np.sum(alpha[i])
        lam_bar = np.sum(lam_upper) + 1e-9

        dt = rng.exponential(1.0 / lam_bar)
        t += dt
        if t >= T:
            break

        # Update R for dt
        for i in range(2):
            R[i] *= np.exp(-beta[i] * dt)

        # Actual intensities
        lam = np.array([mu[i] + np.sum(alpha[i] * R[i]) for i in range(2)])

        # Accept / reject
        u = rng.uniform() * lam_bar
        if u < lam[0]:
            events[0].append(t)
            for i in range(2):
                R[i, 0] += 1.0
        elif u < lam[0] + lam[1]:
            events[1].append(t)
            for i in range(2):
                R[i, 1] += 1.0

    return [np.array(e, dtype=np.float64) for e in events]


# ── helpers ───────────────────────────────────────────────────────────────────


def _make_event_data_stub(all_times: list[np.ndarray], T: float):
    """Minimal duck-type that satisfies HawkesMLE.calibrate() interface."""
    class _Stub:
        n_dims       = len(all_times)
        total_events = sum(len(t) for t in all_times)
        t_span       = T
        source_path  = "<synthetic>"
        dim_stats    = [{"dim": i, "active": len(all_times[i]) >= 50} for i in range(len(all_times))]

        @property
        def active_dims(self):
            return [i for i, s in enumerate(self.dim_stats) if s["active"]]

        def times_for_dim(self, d):
            return all_times[d]

    return _Stub()


# ── tests ─────────────────────────────────────────────────────────────────────


class TestHawkesMLE1D:
    """Calibrate a 1-D Hawkes process and verify parameter recovery."""

    TRUE_MU    = 0.5
    TRUE_ALPHA = 0.4
    TRUE_BETA  = 5.0
    T          = 1000.0

    @pytest.fixture(scope="class")
    def calibrated(self):
        times = simulate_hawkes_1d(
            self.TRUE_MU, self.TRUE_ALPHA, self.TRUE_BETA, self.T, seed=42
        )
        all_times = [times]
        stub      = _make_event_data_stub(all_times, self.T)
        mle       = HawkesMLE(n_dims=1, max_iter=500, n_restarts=3, min_events=50)
        return mle.calibrate(stub), all_times

    def test_mu_within_20pct(self, calibrated):
        result, _ = calibrated
        p = result.params_for(0)
        assert p is not None
        assert abs(p.mu - self.TRUE_MU) / self.TRUE_MU < 0.20, (
            f"μ={p.mu:.4f} vs true {self.TRUE_MU}"
        )

    def test_alpha_within_35pct(self, calibrated):
        # 1-D Hawkes with low branching ratio has high MLE variance; 35% tolerance
        result, _ = calibrated
        p = result.params_for(0)
        assert abs(p.alpha[0] - self.TRUE_ALPHA) / self.TRUE_ALPHA < 0.35, (
            f"α={p.alpha[0]:.4f} vs true {self.TRUE_ALPHA}"
        )

    def test_beta_within_35pct(self, calibrated):
        # 1-D Hawkes with low branching ratio has high MLE variance; 35% tolerance
        result, _ = calibrated
        p = result.params_for(0)
        assert abs(p.beta[0] - self.TRUE_BETA) / self.TRUE_BETA < 0.35, (
            f"β={p.beta[0]:.4f} vs true {self.TRUE_BETA}"
        )

    def test_branching_ratio_stable(self, calibrated):
        """Fitted branching ratio must be < 1 for stationarity."""
        result, _ = calibrated
        p = result.params_for(0)
        assert p.branching_ratio < 1.0, f"branching_ratio={p.branching_ratio:.4f} >= 1"

    def test_log_likelihood_finite(self, calibrated):
        result, _ = calibrated
        p = result.params_for(0)
        assert np.isfinite(p.log_likelihood)
        assert p.log_likelihood < 0  # LL of a point process is typically negative


class TestHawkesMLE2D:
    """Calibrate a 2-D Hawkes and verify cross-excitation is detected."""

    TRUE_MU    = np.array([0.3, 0.4])
    TRUE_ALPHA = np.array([[0.3, 0.2], [0.1, 0.4]])   # alpha[i,j] = j→i
    TRUE_BETA  = np.array([[5.0, 5.0], [5.0, 5.0]])
    T          = 2000.0

    @pytest.fixture(scope="class")
    def calibrated(self):
        times = simulate_hawkes_2d(
            self.TRUE_MU, self.TRUE_ALPHA, self.TRUE_BETA, self.T, seed=7
        )
        stub = _make_event_data_stub(times, self.T)
        mle  = HawkesMLE(n_dims=2, max_iter=500, n_restarts=2, min_events=50)
        return mle.calibrate(stub), times

    def test_both_dims_calibrated(self, calibrated):
        result, _ = calibrated
        assert 0 in result.calibrated_dims
        assert 1 in result.calibrated_dims

    def test_branching_ratios_stable(self, calibrated):
        result, _ = calibrated
        for p in result.dim_params:
            assert p.branching_ratio < 1.0

    def test_excitation_matrix_shape(self, calibrated):
        result, _ = calibrated
        mat = result.excitation_matrix()
        assert mat.shape == (2, 2)

    def test_self_excitation_positive(self, calibrated):
        """Diagonal of excitation matrix (self-excitation) should be > 0."""
        result, _ = calibrated
        mat = result.excitation_matrix()
        assert mat[0, 0] > 0.0
        assert mat[1, 1] > 0.0


class TestGoodnessOfFit:
    """Time-Rescaling GoF on correctly specified model should pass KS test."""

    TRUE_MU    = 0.5
    TRUE_ALPHA = 0.3
    TRUE_BETA  = 4.0
    T          = 2000.0

    @pytest.fixture(scope="class")
    def gof(self):
        times = simulate_hawkes_1d(
            self.TRUE_MU, self.TRUE_ALPHA, self.TRUE_BETA, self.T, seed=99
        )
        all_times = [times]
        stub      = _make_event_data_stub(all_times, self.T)
        mle       = HawkesMLE(n_dims=1, max_iter=500, n_restarts=3, min_events=50)
        result    = mle.calibrate(stub)
        p         = result.params_for(0)
        return HawkesGoodnessOfFit(p, all_times, self.T)

    def test_ks_passes_at_05(self, gof):
        """Well-calibrated model: KS test should not reject at α=0.05."""
        ks = gof.ks_test()
        assert ks["passed"], (
            f"KS test failed: stat={ks['statistic']:.4f}, p={ks['p_value']:.4f}"
        )

    def test_rescaled_times_positive(self, gof):
        tau = gof.compute_rescaled_times()
        assert len(tau) > 0
        assert np.all(tau > 0), "Some rescaled inter-event times are non-positive"

    def test_qq_data_length(self, gof):
        qq = gof.qq_data()
        assert qq["n"] > 0
        assert len(qq["theoretical"]) == len(qq["empirical"])
        assert len(qq["theoretical"]) == qq["n"]


class TestCalibrationResultIO:
    """CalibrationResult serialisation: to_dict / from_dict / save / load."""

    @pytest.fixture(scope="class")
    def result(self):
        times = simulate_hawkes_1d(0.5, 0.4, 5.0, 500.0, seed=1)
        stub  = _make_event_data_stub([times], 500.0)
        mle   = HawkesMLE(n_dims=1, max_iter=200, n_restarts=1, min_events=10)
        return mle.calibrate(stub)

    def test_roundtrip_dict(self, result):
        d       = result.to_dict()
        rebuilt = CalibrationResult.from_dict(d)
        p0      = result.params_for(0)
        p1      = rebuilt.params_for(0)
        assert p1 is not None
        np.testing.assert_allclose(p0.alpha, p1.alpha, rtol=1e-9)
        np.testing.assert_allclose(p0.beta,  p1.beta,  rtol=1e-9)
        assert p0.log_likelihood == pytest.approx(p1.log_likelihood, rel=1e-9)

    def test_save_load(self, result, tmp_path):
        path = tmp_path / "result.json"
        result.save(path)
        assert path.exists()
        loaded = CalibrationResult.load(path)
        assert loaded.calibrated_dims == result.calibrated_dims
        p0 = result.params_for(0)
        p1 = loaded.params_for(0)
        assert p0.mu == pytest.approx(p1.mu, rel=1e-9)
