//! Hawkes-driven limit order book simulator.
//!
//! Maps a 12-dimensional Hawkes process onto LOB events:
//!
//!   Dim  0: Market buy          Dim  1: Market sell
//!   Dim  2: Limit best buy      Dim  3: Limit best sell
//!   Dim  4: Limit deep buy      Dim  5: Limit deep sell
//!   Dim  6: Cancel best buy     Dim  7: Cancel best sell
//!   Dim  8: Cancel deep buy     Dim  9: Cancel deep sell
//!   Dim 10: Modify buy          Dim 11: Modify sell
//!
//! Order sizes follow a log-normal distribution (Gopikrishnan et al., 2000).
//! A U-shape intraday activity profile (Admati & Pfleiderer, 1988) is achieved
//! by thinning the Hawkes event stream with a time-of-day acceptance function:
//!
//!   p_accept(t) = f(t) / peak_factor
//!   f(t) = 1 + (peak_factor − 1) · (2t/T − 1)²

use rand::{Rng, SeedableRng};
use rand::rngs::SmallRng;
use rand_distr::{Distribution, LogNormal};

use crate::hawkes::kernel::{ExcitationKernel, ExponentialKernel};
use crate::hawkes::process::{HawkesEvent, MultivariateHawkes, ProcessError};
use crate::orderbook::book::{OrderBook, OrderBookSnapshot};
use crate::orderbook::order::{Order, Trade};
use crate::orderbook::types::{OrderId, OrderType, Price, Quantity, Side, Timestamp, PRICE_SCALE};

// ── Dimension index constants ─────────────────────────────────────────────────

pub const LOB_DIM: usize = 12;
pub const DIM_MKT_BUY: usize = 0;
pub const DIM_MKT_SELL: usize = 1;
pub const DIM_LIM_BEST_BUY: usize = 2;
pub const DIM_LIM_BEST_SELL: usize = 3;
pub const DIM_LIM_DEEP_BUY: usize = 4;
pub const DIM_LIM_DEEP_SELL: usize = 5;
pub const DIM_CAN_BEST_BUY: usize = 6;
pub const DIM_CAN_BEST_SELL: usize = 7;
pub const DIM_CAN_DEEP_BUY: usize = 8;
pub const DIM_CAN_DEEP_SELL: usize = 9;
pub const DIM_MOD_BUY: usize = 10;
pub const DIM_MOD_SELL: usize = 11;

// ── Config ────────────────────────────────────────────────────────────────────

/// Configuration for a Hawkes LOB simulation run.
#[derive(Debug, Clone)]
pub struct SimulatorConfig {
    /// One tick in fixed-point price units (e.g., `PRICE_SCALE` = 1.0 per tick).
    pub tick_size: i64,
    /// Initial mid-price.
    pub initial_mid: Price,
    /// Initial half-spread in ticks (each side of mid).
    pub initial_half_spread_ticks: i64,
    /// Emit a book snapshot every this many accepted events.
    pub snapshot_interval: usize,
    /// Log-normal μ for order-size sampling.
    pub lognormal_mu: f64,
    /// Log-normal σ for order-size sampling.
    pub lognormal_sigma: f64,
    /// Peak factor for U-shape intraday profile (≥ 1.0; 1.0 = flat).
    pub uday_peak_factor: f64,
    /// Simulated trading-day length in seconds (e.g. 23400 = 6.5 h).
    pub t_max: f64,
    /// Maximum depth offset in ticks for "deep" limit/cancel orders.
    pub max_deep_offset_ticks: i64,
    /// Number of seed levels to initialise on each side of the book.
    pub seed_levels: usize,
}

impl Default for SimulatorConfig {
    fn default() -> Self {
        SimulatorConfig {
            tick_size: PRICE_SCALE,
            initial_mid: Price::from_f64(100.0),
            initial_half_spread_ticks: 1,
            snapshot_interval: 100,
            lognormal_mu: 3.0,
            lognormal_sigma: 1.0,
            uday_peak_factor: 3.0,
            t_max: 23_400.0,
            max_deep_offset_ticks: 10,
            seed_levels: 5,
        }
    }
}

// ── Output types ──────────────────────────────────────────────────────────────

/// One processed Hawkes event and its effect on the LOB.
#[derive(Debug, Clone)]
pub struct SimulationEvent {
    /// Simulation time in seconds.
    pub sim_time: f64,
    /// Hawkes dimension index (0–11).
    pub event_type: usize,
    /// Trades generated by this event (empty for non-crossing orders).
    pub trades: Vec<Trade>,
    /// Optional depth snapshot (emitted every `snapshot_interval` events).
    pub snapshot: Option<OrderBookSnapshot>,
}

/// Aggregated result of a full trading-day simulation.
#[derive(Debug)]
pub struct SimulationResult {
    /// All trades generated during the day.
    pub trades: Vec<Trade>,
    /// Book snapshots with their simulation timestamps (seconds).
    pub snapshots: Vec<(f64, OrderBookSnapshot)>,
    /// Number of Hawkes events accepted (after U-shape thinning).
    pub n_events: usize,
    /// Total simulation length in seconds.
    pub sim_time: f64,
}

// ── Simulator ─────────────────────────────────────────────────────────────────

/// Hawkes-driven LOB simulator.
///
/// Usage:
/// ```ignore
/// let mut sim = HawkesLobSimulator::default_12d().unwrap();
/// let result = sim.simulate_trading_day(42);
/// ```
pub struct HawkesLobSimulator {
    book: OrderBook,
    hawkes: MultivariateHawkes,
    pub config: SimulatorConfig,
    next_order_id: u64,
    // Pre-simulated Hawkes event stream for the current day.
    pending: Vec<HawkesEvent>,
    cursor: usize,
    // Accumulation buffers.
    all_trades: Vec<Trade>,
    snapshots: Vec<(f64, OrderBookSnapshot)>,
    n_accepted: usize,
    rng: SmallRng,
}

impl HawkesLobSimulator {
    /// Construct from an arbitrary Hawkes process and config.
    pub fn new(hawkes: MultivariateHawkes, config: SimulatorConfig) -> Self {
        HawkesLobSimulator {
            book: OrderBook::new(),
            hawkes,
            config,
            next_order_id: 1,
            pending: Vec::new(),
            cursor: 0,
            all_trades: Vec::new(),
            snapshots: Vec::new(),
            n_accepted: 0,
            rng: SmallRng::seed_from_u64(0),
        }
    }

    /// Build a 12-dimensional LOB simulator with calibrated default parameters.
    ///
    /// Background rates follow the empirical ordering:
    ///   market < modify < cancel deep < cancel best < limit deep < limit best
    ///
    /// The excitation matrix uses:
    ///   - Self-excitation      α = 0.20
    ///   - Symmetric-side       α = 0.10 (same event class, opposite side)
    ///   - Cross-class          α = 0.03
    ///   Row sums ≈ 0.20 + 0.10 + 10×0.03 = 0.60 < 1 → process is stable.
    pub fn default_12d() -> Result<Self, ProcessError> {
        let baselines = vec![
            0.5, 0.5, // market buy / sell
            3.0, 3.0, // limit best buy / sell
            2.0, 2.0, // limit deep buy / sell
            1.5, 1.5, // cancel best buy / sell
            1.0, 1.0, // cancel deep buy / sell
            0.5, 0.5, // modify buy / sell
        ];

        let beta = 3.0_f64;
        let alpha = |i: usize, j: usize| -> f64 {
            if i == j {
                0.20
            } else if i / 2 == j / 2 {
                // Same event class (buy vs sell pair), e.g. 0↔1, 2↔3
                0.10
            } else {
                0.03
            }
        };

        let kernels: Vec<Vec<Box<dyn ExcitationKernel + Send + Sync>>> = (0..LOB_DIM)
            .map(|i| {
                (0..LOB_DIM)
                    .map(|j| -> Box<dyn ExcitationKernel + Send + Sync> {
                        Box::new(ExponentialKernel::new(alpha(i, j), beta).unwrap())
                    })
                    .collect()
            })
            .collect();

        let hawkes = MultivariateHawkes::new(baselines, kernels)?;
        Ok(HawkesLobSimulator::new(hawkes, SimulatorConfig::default()))
    }

    /// Reset simulator state: re-simulate a new Hawkes event stream and
    /// reinitialise the order book.
    pub fn reset(&mut self, seed: u64) {
        self.rng = SmallRng::seed_from_u64(seed);
        self.book = OrderBook::new();
        self.next_order_id = 1;
        self.all_trades.clear();
        self.snapshots.clear();
        self.n_accepted = 0;
        self.pending = self.hawkes.simulate(self.config.t_max, seed);
        self.cursor = 0;
        self.initialize_book();
    }

    /// Advance by one accepted Hawkes event.
    ///
    /// Returns `None` when the pre-simulated event stream is exhausted.
    /// Applies U-shape thinning: events near open and close are more likely
    /// to be accepted, creating the empirical U-shaped intraday pattern.
    pub fn step(&mut self) -> Option<SimulationEvent> {
        loop {
            if self.cursor >= self.pending.len() {
                return None;
            }
            let event = self.pending[self.cursor].clone();
            self.cursor += 1;

            // U-shape acceptance: p(t) = f(t) / peak_factor ∈ (0, 1].
            let p_accept = self.time_of_day_factor(event.time) / self.config.uday_peak_factor;
            if self.rng.gen::<f64>() > p_accept {
                continue;
            }

            let ts = Timestamp((event.time * 1e9) as u64);
            let trades = self.apply_event(event.event_type, ts);
            self.all_trades.extend_from_slice(&trades);
            self.n_accepted += 1;

            let snapshot = if self.n_accepted % self.config.snapshot_interval == 0 {
                let snap = self.book.snapshot(10);
                self.snapshots.push((event.time, snap.clone()));
                Some(snap)
            } else {
                None
            };

            return Some(SimulationEvent {
                sim_time: event.time,
                event_type: event.event_type,
                trades,
                snapshot,
            });
        }
    }

    /// Simulate a full trading day from scratch.
    pub fn simulate_trading_day(&mut self, seed: u64) -> SimulationResult {
        self.reset(seed);
        while self.step().is_some() {}
        SimulationResult {
            trades: self.all_trades.clone(),
            snapshots: self.snapshots.clone(),
            n_events: self.n_accepted,
            sim_time: self.config.t_max,
        }
    }

    // ── Internal helpers ──────────────────────────────────────────────────────

    /// f(t) = 1 + (peak − 1)·(2t/T − 1)²
    /// Equals `peak_factor` at t=0 and t=T; equals 1.0 at t=T/2.
    fn time_of_day_factor(&self, t: f64) -> f64 {
        let u = t / self.config.t_max;
        1.0 + (self.config.uday_peak_factor - 1.0) * (2.0 * u - 1.0).powi(2)
    }

    fn next_id(&mut self) -> OrderId {
        let id = self.next_order_id;
        self.next_order_id += 1;
        OrderId(id)
    }

    fn sample_qty(&mut self) -> Quantity {
        let ln = LogNormal::new(self.config.lognormal_mu, self.config.lognormal_sigma).unwrap();
        let raw = ln.sample(&mut self.rng);
        Quantity((raw.round() as u64).max(1))
    }

    fn one_tick(&self) -> Price {
        Price::from_ticks(self.config.tick_size)
    }

    /// Seed the book with `seed_levels` levels on each side around `initial_mid`.
    fn initialize_book(&mut self) {
        let tick = Price::from_ticks(self.config.tick_size);
        let half = Price::from_ticks(self.config.initial_half_spread_ticks * self.config.tick_size);
        let best_bid = self.config.initial_mid - half;
        let best_ask = self.config.initial_mid + half;

        for lvl in 0..self.config.seed_levels as i64 {
            let bid_price = best_bid - Price::from_ticks(lvl * self.config.tick_size);
            let ask_price = best_ask + Price::from_ticks(lvl * self.config.tick_size);
            let qty = Quantity(100 + self.rng.gen_range(0_u64..200));

            let bid_id = self.next_id();
            self.book.insert_resting(Order::new(
                bid_id, Side::Bid, bid_price, qty, Timestamp(0), OrderType::Limit,
            ));
            let ask_id = self.next_id();
            self.book.insert_resting(Order::new(
                ask_id, Side::Ask, ask_price, qty, Timestamp(0), OrderType::Limit,
            ));
        }
        let _ = tick; // used indirectly through price arithmetic above
    }

    /// Dispatch a Hawkes event to the appropriate LOB action.
    fn apply_event(&mut self, event_type: usize, ts: Timestamp) -> Vec<Trade> {
        match event_type {
            DIM_MKT_BUY => self.submit_market(Side::Bid, ts),
            DIM_MKT_SELL => self.submit_market(Side::Ask, ts),
            DIM_LIM_BEST_BUY => self.submit_limit_best(Side::Bid, ts),
            DIM_LIM_BEST_SELL => self.submit_limit_best(Side::Ask, ts),
            DIM_LIM_DEEP_BUY => self.submit_limit_deep(Side::Bid, ts),
            DIM_LIM_DEEP_SELL => self.submit_limit_deep(Side::Ask, ts),
            DIM_CAN_BEST_BUY => {
                self.cancel_best(Side::Bid);
                vec![]
            }
            DIM_CAN_BEST_SELL => {
                self.cancel_best(Side::Ask);
                vec![]
            }
            DIM_CAN_DEEP_BUY => {
                self.cancel_deep(Side::Bid);
                vec![]
            }
            DIM_CAN_DEEP_SELL => {
                self.cancel_deep(Side::Ask);
                vec![]
            }
            DIM_MOD_BUY => {
                self.modify_random(Side::Bid);
                vec![]
            }
            DIM_MOD_SELL => {
                self.modify_random(Side::Ask);
                vec![]
            }
            _ => vec![],
        }
    }

    // ── Order submission helpers ──────────────────────────────────────────────

    fn submit_market(&mut self, side: Side, ts: Timestamp) -> Vec<Trade> {
        let price = match side {
            // Aggressive prices guaranteed to cross all resting liquidity.
            Side::Bid => Price::from_ticks(i64::MAX / 4),
            Side::Ask => Price::from_ticks(1),
        };
        let qty = self.sample_qty();
        let order = Order::new(self.next_id(), side, price, qty, ts, OrderType::Market);
        self.book.add_limit_order(order).trades
    }

    /// Place a limit order one tick inside the current spread.
    /// Suppressed if the book is one-sided and the new price would cross.
    fn submit_limit_best(&mut self, side: Side, ts: Timestamp) -> Vec<Trade> {
        let tick = self.one_tick();
        let price = match side {
            Side::Bid => {
                let candidate = self.book.best_bid()
                    .map(|(p, _)| p + tick)
                    .unwrap_or_else(|| {
                        self.config.initial_mid
                            - Price::from_ticks(
                                self.config.initial_half_spread_ticks * self.config.tick_size,
                            )
                    });
                // Suppress if it would cross the ask.
                if let Some((ba, _)) = self.book.best_ask() {
                    if candidate >= ba {
                        return vec![];
                    }
                }
                candidate
            }
            Side::Ask => {
                let candidate = self.book.best_ask()
                    .map(|(p, _)| p - tick)
                    .unwrap_or_else(|| {
                        self.config.initial_mid
                            + Price::from_ticks(
                                self.config.initial_half_spread_ticks * self.config.tick_size,
                            )
                    });
                if let Some((bb, _)) = self.book.best_bid() {
                    if candidate <= bb {
                        return vec![];
                    }
                }
                candidate
            }
        };
        let qty = self.sample_qty();
        let order = Order::new(self.next_id(), side, price, qty, ts, OrderType::Limit);
        self.book.add_limit_order(order).trades
    }

    /// Place a limit order 2–max_deep ticks behind the best.
    fn submit_limit_deep(&mut self, side: Side, ts: Timestamp) -> Vec<Trade> {
        let offset_ticks =
            self.rng.gen_range(2_i64..=self.config.max_deep_offset_ticks.max(2));
        let offset = Price::from_ticks(offset_ticks * self.config.tick_size);
        let price = match side {
            Side::Bid => {
                self.book.best_bid().map(|(p, _)| p).unwrap_or(self.config.initial_mid) - offset
            }
            Side::Ask => {
                self.book.best_ask().map(|(p, _)| p).unwrap_or(self.config.initial_mid) + offset
            }
        };
        let qty = self.sample_qty();
        let order = Order::new(self.next_id(), side, price, qty, ts, OrderType::Limit);
        self.book.add_limit_order(order).trades
    }

    // ── Cancel / modify helpers ───────────────────────────────────────────────

    /// Cancel the time-priority (front) order at the best price level.
    fn cancel_best(&mut self, side: Side) {
        let id = match side {
            Side::Bid => self
                .book
                .bids
                .iter()
                .next()
                .and_then(|(_, lvl)| lvl.front())
                .map(|o| o.id),
            Side::Ask => self
                .book
                .asks
                .iter()
                .next()
                .and_then(|(_, lvl)| lvl.front())
                .map(|o| o.id),
        };
        if let Some(id) = id {
            self.book.cancel_order(id);
        }
    }

    /// Cancel a random order from levels 2+ (deep side of the book).
    fn cancel_deep(&mut self, side: Side) {
        // Collect IDs first (immutable borrow), then cancel (mutable borrow).
        let ids: Vec<OrderId> = match side {
            Side::Bid => self
                .book
                .bids
                .iter()
                .skip(1)
                .take(5)
                .flat_map(|(_, lvl)| lvl.iter().map(|o| o.id))
                .collect(),
            Side::Ask => self
                .book
                .asks
                .iter()
                .skip(1)
                .take(5)
                .flat_map(|(_, lvl)| lvl.iter().map(|o| o.id))
                .collect(),
        };
        if !ids.is_empty() {
            let idx = self.rng.gen_range(0..ids.len());
            self.book.cancel_order(ids[idx]);
        }
    }

    /// Reduce a random resting order's quantity by half.
    fn modify_random(&mut self, side: Side) {
        let candidates: Vec<(OrderId, Quantity)> = match side {
            Side::Bid => self
                .book
                .bids
                .values()
                .flat_map(|lvl| lvl.iter().map(|o| (o.id, o.quantity)))
                .take(20)
                .collect(),
            Side::Ask => self
                .book
                .asks
                .values()
                .flat_map(|lvl| lvl.iter().map(|o| (o.id, o.quantity)))
                .take(20)
                .collect(),
        };
        if !candidates.is_empty() {
            let idx = self.rng.gen_range(0..candidates.len());
            let (id, qty) = candidates[idx];
            let new_qty = Quantity((qty.0 / 2).max(1));
            if new_qty < qty {
                self.book.modify_order(id, new_qty);
            }
        }
    }

    // ── Strategy interface ────────────────────────────────────────────────────

    /// Current mid-price as a float. Returns `None` if the book is one-sided.
    pub fn mid_price(&self) -> Option<f64> {
        self.book.mid_price().map(|p| p.to_f64())
    }

    /// Place a resting limit order on behalf of an external agent.
    ///
    /// Returns the assigned `OrderId` so the caller can track fills and cancel.
    /// The order is inserted directly without going through the matching engine;
    /// the strategy is responsible for ensuring bid < best_ask and ask > best_bid.
    pub fn place_limit_order(&mut self, side: Side, price: Price, qty: Quantity) -> OrderId {
        let id = self.next_id();
        self.book.insert_resting(Order::new(id, side, price, qty, Timestamp(0), OrderType::Limit));
        id
    }

    /// Cancel an agent order by ID. No-op if the ID is not found.
    pub fn cancel_agent_order(&mut self, id: OrderId) {
        self.book.cancel_order(id);
    }

    /// Read-only access to the order book (for strategy observation).
    pub fn book(&self) -> &OrderBook {
        &self.book
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_12d_constructs_without_error() {
        assert!(HawkesLobSimulator::default_12d().is_ok());
    }

    #[test]
    fn reset_initialises_book_with_both_sides() {
        let mut sim = HawkesLobSimulator::default_12d().unwrap();
        sim.config.t_max = 10.0;
        sim.reset(42);
        assert!(sim.book.best_bid().is_some(), "no bids after reset");
        assert!(sim.book.best_ask().is_some(), "no asks after reset");
    }

    #[test]
    fn simulate_trading_day_produces_events_and_trades() {
        let mut sim = HawkesLobSimulator::default_12d().unwrap();
        // Use short window for test speed.
        sim.config.t_max = 60.0;
        let result = sim.simulate_trading_day(1);
        assert!(result.n_events > 0, "no events in 60 s");
        assert!(!result.snapshots.is_empty(), "no snapshots");
    }

    #[test]
    fn different_seeds_produce_different_event_counts() {
        let mut sim = HawkesLobSimulator::default_12d().unwrap();
        sim.config.t_max = 120.0;
        let r1 = sim.simulate_trading_day(0);
        let r2 = sim.simulate_trading_day(99);
        // Two seeds almost certainly produce different counts.
        assert!(
            r1.n_events != r2.n_events || r1.trades.len() != r2.trades.len(),
            "seeds 0 and 99 produced identical results"
        );
    }

    #[test]
    fn step_returns_none_after_exhaustion() {
        let mut sim = HawkesLobSimulator::default_12d().unwrap();
        sim.config.t_max = 30.0;
        sim.reset(7);
        // Drain all events.
        while sim.step().is_some() {}
        assert!(sim.step().is_none());
    }

    #[test]
    fn event_types_in_valid_range() {
        let mut sim = HawkesLobSimulator::default_12d().unwrap();
        sim.config.t_max = 60.0;
        sim.reset(3);
        while let Some(ev) = sim.step() {
            assert!(ev.event_type < LOB_DIM, "event_type={} out of range", ev.event_type);
        }
    }

    #[test]
    fn snapshots_have_valid_structure() {
        let mut sim = HawkesLobSimulator::default_12d().unwrap();
        sim.config.t_max = 120.0;
        sim.config.snapshot_interval = 10;
        let result = sim.simulate_trading_day(5);
        for (t, snap) in &result.snapshots {
            assert!(*t >= 0.0 && *t <= sim.config.t_max);
            // Snapshot may be empty if book was swept, but timestamp must be set.
            let _ = snap;
        }
    }

    #[test]
    fn best_limit_suppressed_when_spread_is_one_tick() {
        let mut sim = HawkesLobSimulator::default_12d().unwrap();
        sim.config.t_max = 10.0;
        sim.reset(0);

        // Collapse the spread to exactly one tick by inserting synthetic orders.
        let tick = Price::from_ticks(sim.config.tick_size);
        let mid = sim.config.initial_mid;
        // Place bid and ask one tick apart.
        let bid_id = sim.next_id();
        sim.book.insert_resting(Order::new(
            bid_id, Side::Bid, mid, Quantity(10), Timestamp(1), OrderType::Limit,
        ));
        let ask_id = sim.next_id();
        sim.book.insert_resting(Order::new(
            ask_id, Side::Ask, mid + tick, Quantity(10), Timestamp(1), OrderType::Limit,
        ));

        let (bb, _) = sim.book.best_bid().unwrap();
        let (ba, _) = sim.book.best_ask().unwrap();
        assert_eq!(ba - bb, tick, "spread should be exactly 1 tick");

        // A best-buy order would want to go at bb+tick = ba → must be suppressed.
        let trades = sim.submit_limit_best(Side::Bid, Timestamp(2));
        assert!(trades.is_empty(), "order should be suppressed at 1-tick spread");
    }

    #[test]
    fn time_of_day_factor_at_endpoints_equals_peak() {
        let sim = HawkesLobSimulator::default_12d().unwrap();
        let peak = sim.config.uday_peak_factor;
        assert!((sim.time_of_day_factor(0.0) - peak).abs() < 1e-10);
        assert!((sim.time_of_day_factor(sim.config.t_max) - peak).abs() < 1e-10);
    }

    #[test]
    fn time_of_day_factor_at_midday_equals_one() {
        let sim = HawkesLobSimulator::default_12d().unwrap();
        let mid = sim.config.t_max / 2.0;
        assert!((sim.time_of_day_factor(mid) - 1.0).abs() < 1e-10);
    }
}
